name: Wav2Vec2Framework
feature_extractor:
#  _target_: "model.extractor.ConvFeatureExtractor"
  name: ConvFeatureExtractor
  input_size: 1
  extracted_feature_size: 512
encoder:
#  _target_: "model.encoder.ContextualTransformerEncoder"
  name: ContextualTransformerEncoder
  embed_dim: 512
  num_heads: 8
  num_layers: 12

code_vector_size: 512
num_code_vector_groups: 2
num_code_vectors_per_group: 80
mask_time_prob: 0.1
num_mask_time_steps: 5
gumbel_init_temperature: 2
encoder_hidden_size: 512


